- name: Generate ansible github keys
  hosts: all
  vars:
    admin_user: admin
    admin_group: admin
  become: yes
  remote_user: root
  vars_files:
    - group_vars/all/vault.yml
  roles:
    - github_keygen_ansible
