- block:

  # Ensure the .ssh directory exists with correct permissions and ownership
  - name: ensure ~/.ssh directory exists
    ansible.builtin.file:
      path: "/home/{{ admin_user }}/.ssh"
      state: directory
      mode: '0700'
      owner: "{{ admin_user }}"
      group: "{{ admin_group }}"

  # Generate a new SSH key for the GitHub repo if one doesn't already exist
  - name: generate SSH key for GitHub repo
    ansible.builtin.openssh_keypair:
      path: "/home/{{ admin_user }}/.ssh/github-repo_{{ github_repo_name }}"
      type: ed25519
      force: false   # do not overwrite if key already exists
      comment: "{{ github_key_comment | default(admin_user ~ '@' ~ inventory_hostname ~ ' (repo: ' ~ github_repo_name ~ ')') }}"
      mode: '0600'   # private key permission

  # Fix permissions on the public key to be world-readable  
  - name: Set correct permissions on public key
    ansible.builtin.file:
      path: "/home/{{ admin_user }}/.ssh/github-repo_{{ github_repo_name }}.pub"
      mode: '0644'

  - name: Ensure SSH config file exists with proper permissions
    ansible.builtin.file:
      path: "/home/{{ admin_user }}/.ssh/config"
      state: touch
      mode: '0600'
      owner: "{{ admin_user }}"
      group: "{{ admin_group }}"

  - name: Add GitHub SSH config entry for repo {{ github_repo_name }}
    ansible.builtin.blockinfile:
      path: "/home/{{ admin_user }}/.ssh/config"
      owner: "{{ admin_user }}"
      group: "{{ admin_group }}"
      mode: '0600'
      create: yes
      marker: "# {mark} ANSIBLE MANAGED GITHUB KEY {{ github_repo_name }}"
      block: |
        Host github.com-{{ github_repo_name }}
          HostName github.com
          User git
          IdentityFile /home/{{ admin_user }}/.ssh/github-repo_{{ github_repo_name }}
          IdentitiesOnly yes

  # Read the public key content from remote to display it
  - name: Read public key from remote
    ansible.builtin.slurp:
      src: "/home/{{ admin_user }}/.ssh/github-repo_{{ github_repo_name }}.pub"
    register: public_key_content

  # Show the public key for GitHub (decoded and trimmed)
  - name: Show public key for GitHub
    ansible.builtin.debug:
      msg:
        - "SSH public key for {{ github_repo_name }}:"
        - "{{ public_key_content.content | b64decode | trim }}"



  become: yes
  become_user: "{{ admin_user }}"
