---
# Central NAS (Network Attached Storage) Configuration
# group_vars/all/nas.yaml

# Network & Host resolution
nas_backbone_ip: "{{ flashstor_ip }}"
nas_host: "{{ flashstor_host }}"

# Authentication & Target User
nas_user: "admin"
nas_password: "{{ flashstor_admin_password }}"

# Ansible Controller Backup Destination Path
nas_folder_ansible_backup: "/share/server-ansible/backups"
