---
# Role: symlink_files
# Purpose: Create symbolic links from source files to system locations
# 
# This role creates symbolic links between source files (typically in a Git repository)
# and their destination locations (typically in system directories like /etc).
# It supports both full paths and directory-based relative paths, allowing for flexible
# configuration across multiple system directories.
#
# The role:
# 1. Ensures the base destination directory exists (for directory-based approach)
# 2. Processes each file individually to create proper symlinks
# 3. Handles backing up existing files before replacement
# 4. Sets proper ownership on all created symlinks
# 5. Works with both privileged and unprivileged containers/systems

# Ensure the base destination directory exists with proper permissions
# This is primarily used for the directory-based approach
- name: Ensure destination directory exists
  ansible.builtin.file:
    path: "{{ symlink_dest_dir }}"
    state: directory
    owner: "{{ symlink_owner }}"
    group: "{{ symlink_group }}"
    mode: '0755'
  become: true
  when: symlink_dest_dir != ""

# Process each file in the symlink_files list individually
# This allows for fine-grained control and error handling per file
- name: Process each file for symlinking
  include_tasks: process_file.yaml
  loop: "{{ symlink_files }}"
  loop_control:
    loop_var: current_file
    label: "{{ current_file.name }}"
    