--- 
# Default variables for the packages role

# List of base packages to be installed on the system
base_packages:
  - sudo              # Allows permitted users to run commands as another user (typically root)
  - iperf3            # Network bandwidth measurement tool
  - age               # Simple, modern, and secure file encryption tool (used for secrets)
  - jq                # Command-line JSON processor, great for parsing and manipulating JSON data (used for infisical)
  - git               # Distributed version control system for source code management
  - htop              # Interactive process viewer and system monitor (an improved 'top')
  - needrestart       # Evaluates daemon and kernel restart requirements
  - nfs-common        # NFS client utilities (i.e. mount in nfs_mounts role)
  - rsync             # File sync/transfer tool (used by rsync_setup role's server wrapper)

# List of VM specific packages to be installed on the system  
vm_packages:
  - qemu-guest-agent  # QEMU agent

# Combined common packages (base_packages + vm_packages)
common_packages: >-
  {{
    base_packages +
    (vm_packages if (target_type | default('none') == 'vm') else [])
  }}
