---
# Role to install and configure Ansible on Debian/Ubuntu systems
#
# Steps performed:
#  1. Install ansible

# Install ansible package
- name: Install ansible package
  ansible.builtin.apt:
    name: "ansible"
    state: present
