--- 
# Host-specific variables for downloads-001.containers.max.lan
# Network configuration settings specific to this target host

# Network settings
network_interfaces:
  - name: ens18
    id: frontend
    address: 10.24.4.69
    netmask: 255.255.255.0
    gateway: "{{ gateway_ip_containers }}"
    dns_nameservers: "{{ dns_servers_internal }}"
    dns_search: "{{ dns_server_search_internal }}"
    purpose: "frontend (client-facing traffic)"
    firewalled: false

  - name: ens19
    id: backbone
    address: 192.168.1.94
    netmask: 255.255.255.0
    purpose: "backbone (direct NAS traffic)"
    firewalled: true
    allowed_ips:
      - "{{ nas_backbone_ip }}"

# VM
is_lxc: false
