--- 
# -------------------------------------------------------
# Host-specific variables for portal-001.apps.gregrob.net
# -------------------------------------------------------

# Target type
target_type: vm

# Domain settings
domain_root: gregrob.net
domain_sub_prefix: apps
domain_hostname: portal-001

# Network settings
network_interfaces:
  - name: ens18
    id: frontend
    address: 10.24.4.72
    netmask: 255.255.255.0
    gateway: "{{ gateway_ip_apps }}"
    dns_nameservers: "{{ dns_servers_internal }}"
    dns_search: "{{ domain_sub_prefix }}.{{ domain_root }} {{ domain_root }}"
    purpose: "frontend (client-facing traffic)"
    firewalled: false

# List of NFS shares to mount with their corresponding local mount points
nfs_mounts: []
