# Configure Git user name and email for the admin user
- name: Configure Git user settings
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: user.name,  value: "{{ git_name }}" }
    - { name: user.email, value: "{{ git_email }}" }

# Add GitHub to known_hosts to avoid SSH authenticity prompt
- name: Add GitHub to known_hosts
  become: true
  become_user: "{{ admin_user }}"
  ansible.builtin.known_hosts:
    path: "/home/{{ admin_user }}/.ssh/known_hosts"
    name: github.com
    key: "{{ github_ssh_public_key }}"
    state: present
