---
# Included tasks to handle individual GitHub repository cloning with SSH key generation.
# This file is called in a loop for each repository defined in the github_clone role.
#
# Steps performed:
#  1. Set repository-specific variables from the current loop item
#  2. Include github_keygen role to generate SSH keys for the repository - included tasks
#  3. Display confirmation message with public key for manual GitHub setup - included tasks
#  4. Pause execution for user to confirm SSH key has been added to GitHub - included tasks
#  5. Ensure repository destination directory exists with correct permissions - included tasks
#  6. Clone the GitHub repository using the generated SSH key - included tasks

# Loop through the list of GitHub repositories and perform tasks for each
- name: Loop over repos and run tasks
  include_tasks: looped_repo.yaml   # Includes tasks from a separate YAML file
  loop: "{{ github_repos }}"        # Iterates over the list of repos defined in 'github_repos'
  loop_control:
    label: "{{ item.name }}"        # Displays the current repo name in task output for clarity
  vars:
    current_repo: "{{ item }}"      # Sets the current repo item to 'current_repo' for use in the included tasks
