---
# This file is part of the Ansible inventory.

all:
  children:

    ansible:
      hosts:
        ansible-001.containers.max.lan: {}

    lxcs:
      children:
        ansible:

    local:
      hosts:
        localhost:
          ansible_connection: local
