---
# This file is part of the Ansible inventory.

all:
  children:

    configure_target:
      hosts:
        #nut-001.trusted.max.lan: {}
        {}

    ansible:
      hosts:
        ansible-001.containers.max.lan: {}

    docker_privileged:
      hosts:
        frigate-001.containers.max.lan: {}
        jellyfin-001.containers.max.lan: {}
        development-002.containers.max.lan: {}

    docker_unprivileged:
      hosts:
        infisical-001.trusted.max.lan: {}

    # All LXC's
    lxcs:
      hosts:
        ollama-001.apps.gregrob.net:
          ansible_host: ollama-001.apps.gregrob.net

    # All virtual machines
    vms:
      hosts:
        dns-001.dns.gregrob.net:
          ansible_host: dns-001.dns.gregrob.net
        dns-002.dns.gregrob.net:
          ansible_host: dns-002.dns.gregrob.net
        download-001.apps.gregrob.net:
          ansible_host: download-001.apps.gregrob.net
        3dprinter-002.apps.gregrob.net:
          ansible_host: 3dprinter-002.apps.gregrob.net         
          
    # All physical machines
    pms:
      hosts:
        failsafe-002.dns.gregrob.net:
          ansible_host: failsafe-002.dns.gregrob.net
        monitoring-001.mgmt.gregrob.net:
          ansible_host: monitoring-001.mgmt.gregrob.net

    debian_config_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}
        failsafe-002.dns.gregrob.net: {}
        download-001.apps.gregrob.net: {}
        3dprinter-002.apps.gregrob.net: {}
        monitoring-001.mgmt.gregrob.net: {}

        ollama-001.apps.gregrob.net: {}

    network_config_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}
        failsafe-002.dns.gregrob.net: {}
        download-001.apps.gregrob.net: {}
        3dprinter-002.apps.gregrob.net: {}
        monitoring-001.mgmt.gregrob.net: {}

        ollama-001.apps.gregrob.net: {} # Here for completness as LXCs are managed in the Proxmox GUI

    keepalived_dns_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}
        failsafe-002.dns.gregrob.net: {}

    test_target:
      hosts:
        {}

    secrets:
      hosts:
        secrets.max.lan: {}
        
    local:
      hosts:
        localhost:
          ansible_connection: local
  
    git_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
        lxcs:
        vms:
        pms:
    
    update_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
        lxcs:
        vms:
        pms:
