---
# This file is part of the Ansible inventory.

all:
  children:

    configure_target:
      hosts:
        {}

    ansible:
      hosts:
        ansible-001.containers.max.lan: {}

    docker_privileged:
      hosts:
        frigate-001.containers.max.lan: {}
        jellyfin-001.containers.max.lan: {}
        development-002.containers.max.lan: {}

    docker_unprivileged:
      hosts:
        infisical-001.trusted.max.lan: {}

    test_target:
      hosts:
        {}

    secrets:
      hosts:
        secrets.max.lan: {}
        
    local:
      hosts:
        localhost:
          ansible_connection: local

    lxcs:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
    
    git_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
    
    update_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
        