---
# This file is part of the Ansible inventory.

all:
  children:

    configure_target:
      hosts:
        #nut-001.trusted.max.lan: {}
        {}

    ansible:
      hosts:
        ansible-001.containers.max.lan: {}

    docker_privileged:
      hosts:
        frigate-001.containers.max.lan: {}
        jellyfin-001.containers.max.lan: {}
        development-002.containers.max.lan: {}
        #ollama-001.containers.max.lan: {}

    docker_unprivileged:
      hosts:
        3dprinter-001.containers.max.lan: {}
        infisical-001.trusted.max.lan: {}

    # All virtual machines
    vms:
      hosts:
        download-001.containers.max.lan: {}
        dns-001.dns.gregrob.net:
           ansible_host: dns-001.dns.gregrob.net
        dns-002.dns.gregrob.net:
           ansible_host: dns-002.dns.gregrob.net

    # All physical machines
    pms:
      hosts:
        failsafe-002.dns.gregrob.net:
           ansible_host: failsafe-002.dns.gregrob.net

    debian_config_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}
        failsafe-002.dns.gregrob.net: {}

        # The following still need migration to gregrob.net
        download-001.containers.max.lan: {}
        # ollama-001.containers.max.lan: {} # LXC so Proxmox manages the interface in the GUI not Ansible

    network_config_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}
        failsafe-002.dns.gregrob.net: {}

        # The following still need migration to gregrob.net
        download-001.containers.max.lan: {}
        # ollama-001.containers.max.lan: {} # LXC so Proxmox manages the interface in the GUI not Ansible

    keepalived_dns_target:
      hosts:
        dns-001.dns.gregrob.net: {}
        dns-002.dns.gregrob.net: {}

    test_target:
      hosts:
        {}

    secrets:
      hosts:
        secrets.max.lan: {}
        
    local:
      hosts:
        localhost:
          ansible_connection: local

    lxcs:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
    
    git_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
        vms:
        pms:
    
    update_hosts:
      children:
        ansible:
        docker_privileged:
        docker_unprivileged:
        vms:
