---
# This file is part of the Ansible inventory.

all:
  children:

    configure_target:
      hosts:
        {}

    ansible:
      hosts:
        ansible-001.containers.max.lan: {}

    test_target:
      hosts:
        10.24.4.101: {}
        
    local:
      hosts:
        localhost:
          ansible_connection: local

    lxcs:
      children:
        ansible:
    
    git_hosts:
      children:
        ansible:
    
    update_hosts:
      children:
        ansible:
        