- name: Configure Debian LXC Container
  hosts: lxcs
  become: yes
  vars_files:
    - ../group_vars/all/vault.yaml
  roles:
    - packages
    - timezone
    - admin_user
    - git_setup
    - docker_setup
    #- lxc_shares
    #- srv
