- name: Configure Debian LXC Container
  hosts: lxcs
  become: yes
  vars_files:
    - ../group_vars/all/vault.yaml
  roles:
    - disable_systemd_networkd # lxc uses ifupdown, not systemd-networkd
    - packages
    - timezone
    - admin_user
    - git_setup
    - docker_setup
    - lxc_share_user
    - github_clone
    - secrets_connect
