---

- name: Configure a test Debian LXC Container for Ansible
  hosts: test
  become: yes
  vars_files:
    - ../group_vars/all/vault.yaml
    - ../group_vars/all/git-user.yaml
    - ../group_vars/all/github-ansible.yaml
  roles:
    - disable_systemd_networkd # lxc uses ifupdown, not systemd-networkd
    - packages                 # update system and install common packages
    - timezone                 # configure system timezone
    - admin_user               # create admin user with SSH access
    - git_setup                # configure git settings and GitHub SSH key
    - docker_setup             # install and configure Docker with admin access
    - lxc_share_user           # setup LXC shared folder access with proper GID mapping
    - github_clone             # clone GitHub repositories with SSH key authentication
    - secrets_connect          # setup SSH connection to secrets server and decrypt secrets
  
    - ansible_setup           # install and configure Ansible on the container
    