---
# Connect to Secrets Server playbook
# Establishes SSH connection to the secrets server and configures access for secure operations
# This enables containers to access encrypted secrets and sensitive configuration data
#
# Usage:
#   ansible-playbook -i inventories/local/hosts.yaml playbooks/connect-secrets.yaml --ask-vault-pass
#   ansible-playbook -i inventories/local/hosts.yaml playbooks/connect-secrets.yaml --ask-vault-pass -e admin_user=myuser

- name: Make connection to the secrets server
  hosts: configure_target
  gather_facts: yes
  become: yes
  
  vars:
    admin_user: admin
    admin_group: admin
    
  vars_files:
    - ../group_vars/all/vault.yaml
    
  roles:
    - secrets_connect
