- name: Make connection to the secrets server
  hosts: lxcs
  vars:
    admin_user: admin
    admin_group: admin
  become: yes
  vars_files:
    - ../group_vars/all/vault.yaml
  roles:
    - secrets_connect
