- name: Create admin user with git configured
  hosts: lxcs
  become: yes
  vars_files:
    - ../group_vars/all/vault.yaml
  roles:
    - admin_user # create admin user with sudo privileges
    - git_setup # configure git user details and keys for 
