---
# Hello World playbook - demonstrates basic Ansible functionality
# This playbook runs the hello_world role which displays a greeting and executes ls -la

- name: Hello World Playbook
  hosts: all
  gather_facts: yes
  become: false

  vars_files:
    - ../group_vars/all/vault.yaml  
    
  roles:
    - hello_world
